name: Deploy

env:
  DIR_WWW_PROD: /var/www/dominik.codeshape.de/prod
  DIR_WWW_STAGE: /var/www/dominik.codeshape.de/stage
  DIR_BACKUPS: /var/www/dominik.codeshape.de/backups
  DOKKU_WEBAPP: dokkutest-webapp
  DOKKU_BACKEND: dokkutest-backend
  DEPLOY_SERVER: 20.52.186.47

on:
  push:
    branches: [ master ]
  release:
    types: [created]
    tags:
      - 'v*'

jobs:

  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"

  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ github.token }}

    - name: Cloning repo
      uses: actions/checkout@v2

    - name: Push webapp to dokku
      uses: dokku/github-action@master
      with:
        git_remote_url: "ssh://dokku@${{ env.DEPLOY_SERVER }}:22/dokkutest-webapp"
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Push backend to dokku
      uses: dokku/github-action@master
      with:
        git_remote_url: "ssh://dokku@${{ env.DEPLOY_SERVER }}:22/dokkutest-backend"
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
