name: Deploy

env:
  DOKKU_WEBAPP: dokkutest-webapp
  DOKKU_BACKEND: dokkutest-backend
  DEPLOY_SERVER: 20.52.186.47

on:
  push:
    branches: [ master ]
  release:
    types: [created]
    tags:
      - 'v*'

jobs:

  deploy_webapp:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push webapp to dokku
        uses: dokku/github-action@master
        with:
          git_push_flags: '--force'
          git_remote_url: "ssh://dokku@${{ env.DEPLOY_SERVER }}:22/${{ env.DOKKU_WEBAPP }}"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

  deploy_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push backend to dokku
        uses: dokku/github-action@master
        with:
          git_push_flags: '--force'
          git_remote_url: "ssh://dokku@${{ env.DEPLOY_SERVER }}:22/${{ env.DOKKU_BACKEND }}"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
